### ISSUE TITLE
role: mtpereira.nodejs-app

### ISSUE THREAD

**Issue by asebak** [mtpereira/ansible-nodejs-app#1]
Where can I find the source of this role: mtpereira.nodejs-app

**Comment by mtpereira** [comment]
Hello,

Well, mtpereira.nodejs-app _is_ this role! :) Check out on https://galaxy.ansible.com/list#/roles/4213 . If you click on "Github Repo" it'll bring you right back here.

**Comment by asebak** [comment]
@mtpereira alright thanks going to close this now :dancers:
